export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';